# An unique identifier for the head node and workers of this cluster.
cluster_name: DeepGraph-aml

# Cloud-provider specific configuration.
provider:
    type: azure
    location: westus2
    resource_group: rstraineastus_32gb-2-aml
    subscription_id: 20d3c9e4-625d-45e1-ac8a-def90d3c4a88

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    # you must specify paths to matching private and public key pair files
    # use `ssh-keygen -t rsa -b 4096` to generate a new ssh key pair
    ssh_private_key: ~/.ssh/id_rsa
    # changes to this should match what is specified in file_mounts
    ssh_public_key: ~/.ssh/id_rsa.pub
