# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "deepgnn_tf_encoders",
    srcs = [
        "__init__.py",
        "att_encoder.py",
        "han_encoder.py",
    ],
    visibility = ["//visibility:public"],
    deprecation = "This target is deprecated",
)
