name: "Build cache"
description: "Start remote bazel cache proxy to azure storage"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.7'
    - name: Start cache proxy
      shell: bash
      if: runner.os == 'Linux'
      run: |
        go install github.com/buchgr/bazel-remote/v2@v2.4.1
        bazel-remote --azblob.tenant_id=bazelcache --azblob.storage_account=bazelcache --azblob.container_name=cache --azblob.auth_method=shared_key --dir=/tmp/bazelcache --max_size=2 --http_address=localhost:8080 &
        sleep 5 # Give the server time to start
        echo $(curl ${{ inputs.cache_address }}/status)
