# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "deepgnn",
    srcs = [
        "__init__.py",
        "arg_types.py",
        "log_consts.py",
        "logging_utils.py",
        "train_types.py",
    ],
    visibility = ["//visibility:public"],
)
