# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""Common strings used for logging."""

LOG_NAME_DEEPGNN = "deepgnn"
LOG_PROPS_CUSTOM_DIMENSIONS = "custom_dimensions"
LOG_PROPS_EVENT_END_JOB = "deepgnn.end_job"
LOG_PROPS_EVENT_END_WORKER = "deepgnn.end_worker"
LOG_PROPS_EVENT_START_JOB = "deepgnn.start_job"
LOG_PROPS_EVENT_START_WORKER = "deepgnn.start_worker"
LOG_PROPS_KEY_ERR_CODE = "deepgnn.error_code"
LOG_PROPS_KEY_EVENT_TYPE = "deepgnn.event_type"
LOG_PROPS_KEY_JOB_ID = "deepgnn.job_id"
LOG_PROPS_KEY_MODE = "deepgnn.mode"
LOG_PROPS_KEY_MODEL = "deepgnn.model"
LOG_PROPS_KEY_NUM_WORKERS = "deepgnn.num_workers"
LOG_PROPS_KEY_PLATFORM = "deepgnn.platform"
LOG_PROPS_KEY_USER_NAME = "deepgnn.user_name"
LOG_PROPS_KEY_WORKER_INDEX = "deepgnn.worker_index"
LOG_PROPS_PLATFORM_PYTORCH = "deepgnn.pytorch"
LOG_PROPS_PLATFORM_TF = "deepgnn.tensorflow"
