# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "deepgnn",
    imports=["."],
    deps=["//src/python/deepgnn:deepgnn"],
    visibility = ["//visibility:public"],
)
