# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

DOWNSCALE = "downscale"
EMBEDDING_TYPE = "embedding_type"
EMBS_LIST = "embs_list"
ENCODER_MASK = "encoder_mask"
ENCODER_SEQ = "encoder_seq"
ENCODER_TYPES = "encoder_types"
FANOUTS = "fanouts"
FEATURE_ENCODER_STR = "feature_encoder"
FP16_AMP = "amp"
FP16_APEX = "apex"
FP16_NO = "no"
INPUTS = "inputs"
MAX_SENT_CHARS = "max_sentence_characters"
MAX_SEQ_LEN = "max_seq_len"
MODEL_RESIDUAL_ADD = "add"
MODEL_RESIDUAL_CONCAT = "concat"
META_DIR = "metadir"
NODE_DST = "dst"
NODE_FEATURES = "node_feats"
NODE_SRC = "src"
OUTPUT = "output"
PREFIX_CHECKPOINT = "gnnmodel"
PREFIX_EMBEDDING = "embedding"
TERM_TENSOR = "term_tensor"
TRILETTER = "triletter"
TRILETTER_MAX_LETTERS_IN_WORD = "triletter_max_letters_in_word"
VOCAB_FILE = "vocab_file"
