# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

load("@rules_python//python:defs.bzl", "py_test")
load("//config:variables.bzl", "PLATFORM_DEFINES")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "deepgnn_tf_layers",
    srcs = [
        "__init__.py",
        "attention_header.py",
        "base.py",
    ],
    visibility = ["//visibility:public"],
)
