# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "snark_sampler",
    srcs = [
        "__init__.py",
        "sampler/__init__.py",
        "sampler/forest_fire.py",
        "sampler/metric.py",
    ],
    visibility = ["//visibility:public"],
)
