trigger:
  branches:
    include:
    - '*' 
jobs:
- job: sanity_checks
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CredScan@3
    displayName: 'Credscan'
    inputs:
      outputFormat: sarif
      debugMode: false
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'bazelisk build -c dbg //src/cc/lib:wrapper --config=windows'
  - task: BinSkim@3
    inputs:
       toolVersion: Latest
       InputType:   CommandLine
       arguments:   analyze bazel-bin/src/cc/lib/*.dll --recurse