name: "Benchmarks"
description: "Run benchmarks"
inputs:
  disk_cache:
    description: 'Build system cache key'
    required: false
    default: benchmark-${{ runner.os }}-${{ github.ref }}
runs:
  using: "composite"
  steps:
    - run: |
        bazel run -c opt src/cc/lib/benchmark:grpc_benchmark --config=linux
        bazel run -c opt src/cc/lib/benchmark:sampler_benchmark --config=linux
        bazel run -c opt src/cc/lib/benchmark:neighbor_sampler_benchmark --config=linux
      shell: bash
      if: runner.os == 'Linux'
