# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

load("@rules_python//python:defs.bzl", "py_test")
load("//config:variables.bzl", "PLATFORM_DEFINES")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "example_torch_tests",
    srcs = [
        "conftest.py",
    ],
    visibility = ["//visibility:public"],
)
