name: Benchmark

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Run benchmarks
        uses: ./.github/actions/benchmarks
